M48
; DRILL file {KiCad (6.0.7)} date Sat Apr 22 02:03:09 2023
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2023-04-22T02:03:09-05:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.7)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C2.946
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C3.200
%
G90
G05
T1
X119.69Y-91.75
X119.69Y-126.69
X154.63Y-91.75
X154.63Y-126.69
T2
X137.16Y-109.22
T0
M30
